name: Deploy to Render

on:
  push:
    branches: [ main ]
    paths:
      - "api/**"          # deploy only if api/ changed
      - ".github/workflows/deploy-render.yml"
  workflow_dispatch: {}    # allow manual runs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # No need to build here. Render will build from the latest commit.
      - name: Trigger Render Deploy
        run: curl -fsS -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
